/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_if_2;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner miScan = new Scanner(System.in);
        
        System.out.println("Introduzca un número del día de la semana: ");
        int dia = miScan.nextInt();
        
        if(dia == 1){
            
            System.out.println("¡Es Lunes!");
        }
        else if (dia == 2){
            
            System.out.println("¡Es Martes!");
        }
        else if(dia == 3){
            
            System.out.println("¡Es Miércoles!");
        }
        else if(dia == 4){
            
            System.out.println("¡Es Jueves!");
        }
        else if(dia == 5){
            
            System.out.println("¡Es Viernes!");
        }
        else if(dia == 6){
            
            System.out.println("¡Es Sábado!");
        }
        else if(dia == 7){
            
            System.out.println("¡Es Domingo!");
        }
        else{
            
            System.out.println("Ese no es ningún día de la semana.");
        }
    }
}

